# docker-compose.yml
version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      # Mount the AWS credentials from the host if running on EC2/ECS
      - ~/.aws:/root/.aws:ro
      # Mount the instance metadata directory if running on EC2
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - S3_BUCKET=${S3_BUCKET}
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"